apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-maven-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-maven-app
  template:
    metadata:
      labels:
        app: spring-maven-app
    spec:
      containers:
        - name: spring-maven-app
          image: randyaji/spring-maven-app:latest
          ports:
            - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: spring-maven-app-service
spec:
  selector:
    app: spring-maven-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: NodePort
